SELECT SUBSTR(PHONE_NUMBER,1,3) "Operator",COUNT(PHONE_NUMBER) "Total" FROM HR.EMPLOYEES GROUP BY SUBSTR(PHONE_NUMBER,1,3)

WITH QUERY AS
(
SELECT SUBSTR(PHONE_NUMBER,1,3) "Operator" ,COUNT(PHONE_NUMBER) "Total"
FROM HR.EMPLOYEES 
GROUP BY SUBSTR(PHONE_NUMBER,1,3))
SELECT *
FROM QUERY
PIVOT
(
SUM("Total") FOR "Operator"  IN (011,515,650,603,590)
)

