DESCRIBE HR.EMPLOYEES

CREATE TABLE EMP   
(
    EMPLOYEE_ID NUMBER(6,0) NOT NULL,
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(25) NOT NULL,
    EMAIL VARCHAR2(25) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR2(10) NOT NULL,
    SALARY NUMBER(8,2),
    COMMISSION_PCT NUMBER(2,2),
    MANAGER_ID NUMBER(6,0),
    DEPARTMENT_ID NUMBER(4,0),
    PRIMARY KEY(EMPLOYEE_ID)
)

INSERT INTO EMP(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID)
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID
FROM HR.EMPLOYEES

SELECT * FROM EMP

INSERT INTO EMP(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID)
VALUES(15000,'Ayşe','Nur','aysenurbilge01@gmail.com','17-JUN-03','IT_PROG',15000,103,60)

UPDATE EMP SET PHONE_NUMBER=5520895580,SALARY=20000 WHERE EMPLOYEE_ID=15000

SELECT * FROM EMP WHERE EMPLOYEE_ID=15000

DELETE FROM EMP WHERE EMPLOYEE_ID=15000

DROP TABLE EMP
